# Generated by Django 2.2.28 on 2024-09-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_flight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='Flight_model',
        ),
    ]
