# Generated by Django 2.2.28 on 2024-09-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20240911_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_model',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
