# Generated by Django 2.2.28 on 2024-09-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_flight_model_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceIncrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment_value', models.FloatField(default=0)),
            ],
        ),
    ]
