# Generated by Django 2.2.28 on 2024-09-12 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_priceincrement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThriveAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first_name', max_length=100)),
                ('last_name', models.CharField(default='last_name', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('approval_status', models.BooleanField(default=False)),
                ('thrive_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thrive_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
