# Generated by Django 2.2.28 on 2024-09-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_thriveadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thriveadmin',
            old_name='thrive_admin',
            new_name='admin',
        ),
    ]
