# Generated by Django 2.2.28 on 2024-09-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20240912_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceincrement',
            name='increment_value',
            field=models.IntegerField(default=0),
        ),
    ]
