# Generated by Django 2.2.28 on 2024-09-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20240921_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_model',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
